services:

  web:
    build: .
    container_name: launchpad_web
    command: python -u app.py
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
      - ./exports:/app/exports
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

  scheduler:
    build: .
    container_name: launchpad_scheduler
    command: python -u scheduler_job.py
    volumes:
      - ./data:/app/data
      - ./exports:/app/exports
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped